export const IActions={
    REGISTER_FIREBASE:"REGISTER_FIREBASE",
    LOGIN_FIREBASE:"LOGIN_FIREBASE",
    LOGOUT_FIREBASE:"LOGOUT_FIREBASE",
    AUTH_TOKEN:"AUTH_TOKEN",
    ME_FIREBASE:"ME_FIREBASE",
    //
    TOGGLE_MESSAGE:"MESSAGE_TOGGLE"
}